### PR TITLE
Completing redux installation and removing GameContext

### PR DESCRIPTION
**Pull request by jgordley**
Finished up implementing redux, no longer having a global gamecontext (File removed) and now context is only used for things like textfield values, etc.

### CODE REVIEW

**Comment by jgordley** [comment]
[Implement Redux to Playground Code](https://trello.com/c/zEo9ATp4/44-implement-redux-to-playground-code)

**Comment by chase-saca** [comment]
I took out the isHost action from the gameStats reducer because we can simply check if username === 'Host', like we do in App. Other than that I made a few other small changes to tidy things up.

**Comment by jgordley** [comment]
Thanks legend, we'll get Ronan to help us fix the github actions build and be able to merge everything in tomorrow.

**Comment by chase-saca** [comment]
I am not sure why the check is failing, it looks like an npm module isn't found: 'ajv/dist/compile/codegen' MODULE NOT FOUND. Would pushing our package.json fix this problem? I ran npm install in both the client and server so they should be up-to-date, but I never pushed my package.json.

**Comment by jgordley** [comment]
Yeah maybe that would do it, could you give it a try? When running `npm run build` locally everything seems fine so maybe its a missing dependency in the repo

**Review by chase-saca — APPROVED** [review]
Code looks great! Thanks Jack for finishing up the implementation of redux with GameController. Once the final check can be passed or overridden, let's merge.

**Comment by aleone2** [comment]
Code looks really good, clean and now so uniform and central! Had a look at the errors, also dont understand why they are failing both run locally and npm run build works on my local machine as well once those are set all looks good to me! Nice work thanks guys

**Pull request merged**
