### PR TITLE
Fixing negative scores on leaderboard

### PR DESCRIPTION
**Pull request by katleigh13**
Changed scores on leaderboard to stop at 0 instead of declining into negative numbers

### CODE REVIEW

**Review by jgordley — APPROVED** [review]
Looks good!

**Comment by chase-saca** [comment]
Hi @katleigh13 ! Great job on the leaderboard page. If you look at the issue for the negative scores, you should also make a small change on the PlayerPage, as well. Here are some guidelines:

LeaderboardPage/index.tsx: In this file, we handle attack messages from each player to show on the host screen. In the function handleAttack, once the target's score is decreased, you must check if the score is negative and instead set the score to zero.
PlayerPage/index.tsx: In this file, we handle attack messages from each player to show on the player screen. In the function handleAttack, we dispatch an action to decrease the player's score in the state. You must instead first decrease the score by 50 (attack damage), set the score to zero if it is negative, and then dispatch the action with the score.

Comment back if you have any questions! :)

**Review by chase-saca — CHANGES_REQUESTED** [review]
Add in the small change to PlayerPage.

**Review by chase-saca — APPROVED** [review]
These changes look great! Thank you so much for your contribution and fixing the bug. :)

**Pull request merged**
