### PR TITLE
Testing npm dependencies to pass failed check

### PR DESCRIPTION
**Pull request by chase-saca**

### CODE REVIEW

**Comment by chase-saca** [comment]
Huh.. added package.json on top of our commits for the 'finishing redux implementation' and the checks still don't pass.. not sure why since all the dependencies and modules should be up-to-date?

**Comment by chase-saca** [comment]
Furthermore, the package.json addition ran the 12.x check too, but it also failed due to the same error before with the 14.x failing still as well...

**Comment by chase-saca** [comment]
@rpmccarter thanks for fixing the failing check - can you try this on the official pull request finishing-redux-implementation?

**Comment by rpmccarter** [comment]
@chase-saca do you think it makes sense to remove the 12.x and 14.x checks for server and client? This is obviously going to make our code a bit less flexible but if we're never going to use 12.x or 14.x Node.js platforms then I think it would be fine

**Pull request closed without merging**
